# -*- coding: utf-8 -*-
"""portfolio-risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMht-foCm2om0uBBlEep-dsM2Jo1dfz8
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import numpy as np

# Download multiple stock data
tickers = ["AAPL", "MSFT", "AMZN"]
data = yf.download(tickers, start="2024-01-01", end="2024-12-31")['Close']

# Daily returns
returns = data.pct_change().dropna()

# Portfolio weights
weights = [0.4, 0.3, 0.3]

# Portfolio daily returns
portfolio_returns = (returns * weights).sum(axis=1)

# Portfolio cumulative growth (starting with $1)
cumulative = (1 + portfolio_returns).cumprod()

# Plot
cumulative.plot(figsize = (10, 5))
plt.title("Portfolio Growth of $1 Investment (2024)")
plt.ylabel("Portfolio Value ($)")
plt.show()

# Calculate risk metrics
volatility = portfolio_returns.std() * np.sqrt(252) # Annualized volatility
annual_return = portfolio_returns.mean() * 252 # Annualized return
risk_free_rate = 0.05 # Assume 5% risk-free rate
sharpe_ratio = (annual_return - risk_free_rate) / volatility

# Print results
print("Annual Return: ", round(annual_return, 4))
print("Volatility: ", round(volatility, 4))
print("Sharpe Ratio: ", round(sharpe_ratio, 4))

